import type { Metadata } from "next";
import { El_Messiri } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import StoreProvider from "./StoreProvider";

const ElMessiri = El_Messiri({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={ElMessiri.className}>
          <Nav />
          {children}
          <Footer />
        </body>
      </StoreProvider>
    </html>
  );
}
